config/routes.rb
Steamgrid::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      match 'top_picture' => "api#top_picture"
    end

    namespace :v2 do
      match 'consoles' => 'consoles#list', :via => :get
      match 'consoles/search' => 'consoles#search', :via => :get
      match 'console/:id' => 'consoles#show', :via => :get
      match 'console/:id/games' => 'consoles#games', :via => :get
      match 'games/search' => 'games#search', :via => :get
      match 'game/:id' => 'games#show', :via => :get
      match 'game/:id/top_rated_picture' => 'games#top_rated_picture', :via => :get
    end
  end

  scope "/api", :module => "api/v1" do
    match 'top_picture' => "api#top_picture"
  end
  
  resources :games, :except => [:edit, :update]
  match 'games/:id/mark_duplicate' => 'games#mark_as_duplicate', :via => :post, :as => :mark_as_duplicate
  match 'consoles/:id' => 'games#console', :as => :console
  
  match 'pictures' => "pictures#create", :via => "post", :as => :pictures
  match 'pictures/:id/vote' => "pictures#vote", :via => "post", :as => :vote_picture

  root :to => 'games#find'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :console
  has_many :pictures, :dependent => :destroy
  attr_accessible :name
  attr_accessible :name, :console_id, :duplicate, :as => :admin
  
  self.per_page = 30
  
  scope :duplicates, where(:duplicate => true)
  
  searchable do
    text :name
    boolean :duplicate
    integer :console_id
  end
  
  def self.easy_search(string, options={})
    options.reverse_merge! :console_id => nil, :page => 1, :per_page => Game.per_page
    search_output = Game.solr_search do
      fulltext Game.escape_solr_string(string)
      with :duplicate, false
      with :console_id, options[:console_id] unless options[:console_id].nil?
      paginate :page => options[:page], :per_page => options[:per_page]
    end
    search_output.results
  end
  
  def self.escape_solr_string(string)
    formatted = string.downcase.gsub /([\\\+\-\&\|\!\(\)\{\}\[\]\^\~\*\?\:\"\; ])/ do |specialchar|
      "\\" << specialchar
    end
    return formatted
  end

  def top_picture_url
    picture = self.top_rated_picture
    picture.image_url unless picture.nil?
  end

  def top_rated_picture
    self.pictures.find_with_reputation(:votes, :all, :order => "votes desc", :limit => 1).first
  end

  def as_json(options={})
    default_options = {
      :only => [
        :id,
        :name,
        :console_id,
      ]
    }
    # By default, as_json only evaluates EITHER only or except. To make this method transparent
    # to the caller, if the caller added a field to 'except' we need to remove it from our default
    # 'only'.
    default_options[:only] -= default_options[:only] & options[:except] if options[:except]
    super(default_options.merge(options))
  end
end

app/controllers/api/v2/games_controller.rb
class Api::V2::GamesController < Api::V2::BaseApiController
  # Searches for games with names matching the query parameter `q`. Results
  # are paginated, and are ordered by relevance.
  #
  # Parameters:
  # q         - The query string to match games against
  # page      - The page of results to display, for pagination. If no page is
  #             specified then it defaults to 1
  # per_page  - The number of results to display per page, to be used in
  #             conjunction with the page parameter. Functionally equivalent
  #             to a 'limit' when page is 1
  def search
    raise Exceptions::APIError, "Missing search query. Did you forget to pass 'q='?" unless params.include? :q

    games = Game.easy_search(params[:q], :page => params[:page], :per_page => params[:per_page] )
    render :json => { :error => nil, :total_pages => games.total_pages, :games => games }, :methods => [:top_picture_url]
  end

  # Gets all information related to a single game. Along with metadata, this
  # includes all of the pictures that have been submitted for the game, along
  # with the pictures score and the current user's vote on that picture.
  #
  # Parameters: None
  def show
    id = params[:id]
    game = Game.find_by_id(id)
    raise Exceptions::APIError, "Unable to find Game with id '#{id}" if game.nil?

    # TODO: ORDER PICTURES BY SCORE
    render :json => { :error => nil, :game => game }, :include => {
      :pictures => {
        :only => [:image_url],
        :methods => [:score],
        # TODO: Right now we have no way of authenticating in the API, so
        # current_user will always be nil, resulting in a vote of 0. Better to
        # just not expose this field until after we have authentication
        # :vote_for_user => current_user,
      }
    }
  end

  # Gets the highest rated picture for a given game.
  #
  # Parameters: none
  def top_rated_picture
    id = params[:id]
    game = Game.find_by_id(id)
    raise Exceptions::APIError, "Unable to find Game with id '#{id}'" if game.nil?

    render :json => { :error => nil, :url => game.top_picture_url }
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    add_crumb("'#{params[:q]}'",games_path(:q => params[:q]))
    @matches = Game.easy_search params[:q], :page => params[:page]
    respond_to do |format|
      format.html # search.html.erb
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    add_crumb(@game.console.name,console_path(@game.console))
    add_crumb(@game.name,game_path(@game))
    
    # @pictures = @game.pictures
    @pictures = @game.pictures.find_with_reputation(:votes, :all, :order => "votes desc")
    @top_picture = @pictures.shift
    @new_picture = Picture.new
    @new_picture.game_id = @game.id
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new
    if params[:console]
      @game.console = Console.where(:shortname => params[:console]).first
      add_crumb(@game.console.name,console_path(@game.console))
    end
    
    @consoles = Console.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @game }
    end
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new()
    @game.name = params[:game][:name]
    @game.console_id = params[:game][:console_id]
    
    respond_to do |format|
      if @game.save
        # @game.populate_inverted_index
        format.html { redirect_to @game, :notice => 'Game was successfully created.' }
        format.json { render :json => @game, :status => :created, :location => @game }
      else
        format.html { render :action => "new" }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
  
  def find
    respond_to do |format|
      format.html # find.html.erb
    end
  end
  
  def console
    @num_games = 30
    @console = Console.find(params[:id])
    add_crumb(@console.name,console_path(@console))
    @matches = @console.games.where(:duplicate => false).paginate(:page => params[:page])
    respond_to do |format|
      format.html # console.html.erb
    end
  end
  
  def mark_as_duplicate
    @game = Game.find(params[:id])
    @game.duplicate = true
    @game.save
    flash[:notice] = "Thanks for helping out! We will look into your report"
    redirect_to(:back)
  end
end

app/helpers/api/v2/games_helper.rb
module Api::V2::GamesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br />
  <div class="field">
    <%= f.label :console %>
    <%= collection_select("game", "console_id", @consoles, :id, :name) %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_table.html.erb
<% if @matches.empty? %>
  <table class="table table-bordered table-striped">
    <tr>
      <th>Name</th>
    </tr>
    <tr>
      <td>There's nothing here!</td>
    </tr>
  </table>
<% else %>
  <table class="game-table table table-bordered table-striped">
    <tr>
      <th>Top Image</th>
      <th width='80%'>Name</th>
    </tr>
    <% @matches.each do |game| %>
      <tr>
        <td>
          <%= game.pictures.empty? ? 'No image!' : link_to(image_tag(game.top_rated_picture.image_url, class: 'table-image'), game) %>
        </td>
        <td class="game-table-name-cell">
          <%= link_to button_tag("Mark as duplicate", :class => "pull-right btn btn-mini btn-primary"), mark_as_duplicate_path(game), :method => :post, :class => "duplicate-link" %>
          <h4><%= link_to game.name, game %></h4>
          <%= link_to game.console.name, game.console if show_console %><p><%= game.pictures.count %> other images</p>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>
<%= will_paginate @matches, :renderer => BootstrapPagination::Rails %>
<script>
$(document).ready(function(){
  $(".duplicate-link").hide();
  $(".game-table-name-cell").hover(
    function() {
      $(this).find('.duplicate-link').show();
    }, 
    function() {
      $(this).find('.duplicate-link').hide();
    }
  );
});
</script>

app/views/games/_vote.html.erb
<% vote = picture.user_vote(current_user) %>
<ul class="vote pull-left">
  <% if vote == 1 %>
    <li class="vote-arrow"><%= image_tag('upvoted.png') %></li>
  <% else %>
    <li class="vote-arrow"><%= link_to image_tag('not_upvoted.png'), vote_picture_path(picture, :type => :up), :method => :post %></li>
  <% end %>
  <li class="spacer"></li>
  <li class="vote-count"><%= picture.reputation_for(:votes).to_i %></li>
  <li class="spacer"></li>
  <% if vote == -1 %>
    <li class="vote-arrow"><%= image_tag('downvoted.png') %></li>
  <% else %>
    <li class="vote-arrow"><%= link_to image_tag('not_downvoted.png'), vote_picture_path(picture, :type => :down), :method => :post %></li>
  <% end %>
</ul>

app/views/games/console.html.erb
<%= link_to button_tag('New Game', :class => "btn btn-primary pull-right"), new_game_path(:console => @console.shortname) %>
<h1><%= @console.name %></h1>
<%= render 'table', :show_console => false %>

app/views/games/find.html.erb
<table class="game-search-table">
  <tbody>
    <tr>
      <td>
        <div class="game-search-logo">
          <%= image_tag('Logo.png') %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <%= form_tag games_path, :method => :get, :class => "form game-search" do %>
          <div class="fields">
            <%= text_field_tag :q %>
            <%= button_tag('<i class="icon-search icon-white"></i>'.html_safe, :type => "submit", :class => "btn btn-primary") %>
          </div>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<script>
$(document).ready(function() {
  $(".game-search input[type=text]").focus();
});
</script>

app/views/games/index.html.erb
<%= link_to button_tag('New Game', :class => "btn btn-primary pull-right"), new_game_path %>
<h1>Search Results</h1>
<%= render 'table', :show_console => true %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<% if @top_picture.present? %>
  <section id="top-picture-section">
    <div class="page-header">
      <h1>Top Rated</h1>
    </div>
    <div class="hero-unit">
      <div class="top-picture">
        <%= render 'vote', :picture => @top_picture %>
        <%= image_tag(@top_picture.image_url) %>
      </div>
    </div>
  </section>
<% end %>

<%# Display all of the pictures %>
<section id="all-picture-section">
  <div class="page-header">
    <h1>All Pictures</h1>
  </div>
  <% if @pictures.count != 0 %>
    <table id="all-pictures-table">
      <% @pictures.each do |picture| %>
        <tr>
          <td><%= render 'vote', :picture => picture %></td>
          <td><%= image_tag(picture.image_url) %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p>Nothing has been added yet!</p>
  <% end %>
</section>

<% if user_signed_in? %>
  <section id="add_picture_section">
    <div class="page-header">
      <h1>Add Picture</h1>
    </div>
    <%= form_for @new_picture, :html => {:class => "form"} do |f| %>
      <%= f.hidden_field :game_id %>
      <%= f.file_field :image %>
      <br />
      <br />
      <%= f.submit %>
    <% end %>
  </section>
<% end %>