config/routes.rb
Steamgrid::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      match 'top_picture' => "api#top_picture"
    end

    namespace :v2 do
      match 'consoles' => 'consoles#list', :via => :get
      match 'consoles/search' => 'consoles#search', :via => :get
      match 'console/:id' => 'consoles#show', :via => :get
      match 'console/:id/games' => 'consoles#games', :via => :get
      match 'games/search' => 'games#search', :via => :get
      match 'game/:id' => 'games#show', :via => :get
      match 'game/:id/top_rated_picture' => 'games#top_rated_picture', :via => :get
    end
  end

  scope "/api", :module => "api/v1" do
    match 'top_picture' => "api#top_picture"
  end
  
  resources :games, :except => [:edit, :update]
  match 'games/:id/mark_duplicate' => 'games#mark_as_duplicate', :via => :post, :as => :mark_as_duplicate
  match 'consoles/:id' => 'games#console', :as => :console
  
  match 'pictures' => "pictures#create", :via => "post", :as => :pictures
  match 'pictures/:id/vote' => "pictures#vote", :via => "post", :as => :vote_picture

  root :to => 'games#find'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConsoleGrid</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-static-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "ConsoleGrid", root_path, :class => "brand" %>
        <%= form_tag games_path, :method => :get, :class => "navbar-search pull-left" do %>
          <input type="text" class="search-query" placeholder="Search" name="q">
        <% end %>
        <ul class="nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Consoles<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% consoles = Console.all %>
              <% consoles.each do |console| %>
                <li><%= link_to console.name + " - " + console.shortname, console %></li>
              <% end %>
              <li>
                <a href="http://steamcommunity.com/groups/IceRM/discussions/0/666826251248041382/">
                  <small>Something missing?, post a suggestion here</small>
                </a>
              </li>
            </ul>
          </li>
        </ul>
        <ul class="nav pull-right">
        

          <% if user_signed_in? %>
              <li><%= link_to current_user.email, "#" %></li><li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Sign In
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu" id="login-dropdown">
                <%= form_for(:user, :url => session_path(:user)) do |f| %>
                  <%= f.text_field :email %>
                  <%= f.password_field :password %>
                  <li><label class="checkbox"><%= f.check_box :remember_me %> Remember me</label></li>
                  <li><%= f.submit 'Sign in', class: 'btn btn-block' %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Create account", new_user_registration_path %></li>
                  <li><%= link_to "Forgot your password?", new_password_path(:user) %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>" style="margin-top:20px">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
    <% num_crumbs = @breadcrumbs.count %>
    <% if num_crumbs > 1 %>
      <ul class="breadcrumb" style="margin-top:20px">
        <% @breadcrumbs.each_index do |index| %>
          <% crumb = @breadcrumbs[index] %>
          <li>
            <%= link_to crumb[:title], crumb[:link] %>
            <% if num_crumbs != index + 1 %>
              <span class="divider">></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <%= yield %>
  </div>
  <br />
  <br />
  <br />
</body>
</html>